### ISSUE TITLE
Awkward underline wrapping

### ISSUE THREAD

**Issue by paulhiggs** [75lb/command-line-usage#34] opened 2021-06-27 07:14 UTC
The underlining of indented text does not wrap cleanly across lines, see attached screenshot
This was produced with the following
````
const commandLineHelp=[
	{
		header: 'DVB Central Service Registry',
		content: 'An implementaion of a DVB-I Service List Registry'
	},
	{
		header: 'Synopsis',
		content: '$ node csr <options>'
	},
	{
		header: 'Options',
		optionList: optionDefinitions
	},
	{
		header: 'Client Query',
		content: '{underline <host>}:{underline <port>}/query[?{underline arg}={underline value}(&{underline arg}={underline value})*]',
	},
	{
		content: [
			{header:'{underline arg}'},
			{name:'regulatorListFlag', summary:'Select only service lists that have the @regulatorListFlag set as specified (true|false)'},
			{name:'Delivery[]', summary:'Select only service lists that use the specified delivery system (dvb-t|dvb-dash|dvb-c|dvb-s|dvb-iptv)'},
			{name:'TargetCountry[]', summary:'Select only service lists that apply to the specified countries (form: {underline ISO3166 3-digit code})' },		
			{name:'Language[]', summary:'Select only service lists that use the specified language (form: {underline IANA 2 digit language code})'},		
			{name:'Genre[]', summary:'Select only service lists that match one of the given Genres'},		
			{name:'Provider[]', summary:'Select only service lists that match one of the specified Provider names'}
		]
	},
	{	content:'note that all query values except Provider are checked against constraints. An HTTP 400 response is returned with errors in the response body.'},
	{
		header: 'About',
		content: 'Project home: {underline https://github.com/paulhiggs/dvb-i-tools/}'
	}
];
````
![Screenshot 2021-06-27 081131](https://user-images.githubusercontent.com/3158807/123535961-76aded00-d71f-11eb-87d4-e0fe0ae7cf84.jpg)

**Comment by 75lb** [comment] 2021-06-28 12:29
Duplicate of https://github.com/75lb/wordwrapjs/issues/3. 

Any input appreciated on this one, the fix doesn't have to be perfect. I'll tidy things up before release.

**Closed** 2021-06-28 12:29 UTC
Labels: enhancement, help wanted
